encoding: utf-8

exclude:
  - .gitignore
  - TODO.txt
  - _pages/secretariat.md
  - Gemfile
  - Gemfile.lock
  - dsmun18.sublime-*
  - pre-commit

include:
  - _pages
  - .htaccess

collections:
  committees:
    output: true
    permalink: /committees/:name

defaults:
  -
    scope:
      path: ""
      type: committees
    values:
      layout: committee

plugins:
  - jekyll-sitemap

committees_list:
  - unsc
  - disec
  - ecosoc
  - eic
  - iaea
  - ipc
  - ls
  - scrt
  - specpol
  - third-reich
  - unhrc
  - unodc
